<div class="container shadow-sm bg-white rounded">
    <h1><?php echo $title; ?></h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quis qui praesentium aut debitis dolores quasi assumenda eaque perspiciatis, ratione neque architecto mollitia doloribus, blanditiis non voluptatibus numquam hic cum.</p>
</div>