<div class="container shadow-sm bg-white rounded">
    <h1><?php echo $title; ?></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
</div>
