<div id="container">
    <h1><?php echo $title; ?></h1>
    <div id="body">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio esse dolore officiis, velit vero suscipit ipsam repellat voluptatibus perferendis consectetur, repellendus laborum corporis. Modi eligendi praesentium, nesciunt facere placeat perferendis?</p>
    </div>
</div>
